### ISSUE TITLE
Live writing of CSV file on each event

### ISSUE THREAD

**Issue by EliotGann** [bluesky/suitcase-csv#14]
Maksim helped me a lot today, but we basically ran into the problem that the csv suitcase (unlike the tif suitcase) does not output a usable file during a scan (we are running it with the runrouter setup).  It would be very nice if at each event, a line could just be appended to a csv file which could be read by a different program live, so then my analysis can get all of the information it needs for the corrections of each tif live as they are being written.  It looks like now it keeps the file open for the whole scan, and only closes it and allows another program to access it at the end.

**Comment by awalter-bnl** [comment]
HI @EliotGann, thanks for the issue. This was debated in detail when we wrote `suitcase-csv`, with the only solution we could find having a significant issue that meant it would be practically unusable.

Currently we are using `pandas.dataframe.to_csv(..)` to write out the file. At present we are actually appending to the file line by line, but the file is kept open until the scan is finished. Text based files (like csv) do not allow (at least as far as I know) a file to be read if it is open by another program, and this is the base of the issue.

In principle we could close the file after we write each line, and open it prior to writing. However in order to 'read' the file we would need to synchronize with the writing part of the serializer, which seems like it would be almost impossible, and prone to frequent crashes.

So unfortunately I don't think that this suggestion is practically possible. Does anyone else have any good ideas on how to do this?

In order to perform on the fly analysis, I strongly suspect that it would be easier to move your analysis routines to python and write them as a serializer, which bypasses the file writing entirely.

**Comment by mrakitin** [comment]
I thought I posted it before today. Here we go.

Maybe `a+` can be used in that case. However it will require reworking how we open/close the file. See https://stackoverflow.com/a/30566011/4143531 for more options.

**Comment by awalter-bnl** [comment]
I am not sure this resolves the underlying issue. `a+` allows the same program to read and write. I don't think it allows multiple programs (in this case the serializer and the analysis program) to open the same file at the same time.

**Comment by EliotGann** [comment]
I don’t understand the issue, text files are read while writing all the time (any log file for instance) but wouldn’t outputting a single csv file for each tif file/event be the obvious solution?  Can that be an option at least-it would be one tiff file and one csv file for the values related to that tiff?  Right now I’m just writing out a simple manual csv txt file which works fine, I just open write and close, I can monitor the file and see the values pop up.  It is certainly usable.  Perhaps the real solution is just writing the entire event into a hdf5 so it is all accessible... and yes, live analysis in python too... but in the meantime this would be a workable solution.

**Comment by danielballan** [comment]
> I don’t understand the issue, text files are read while writing all the time (any log file for instance)

Yes. I think some wires may be crossed in the comments above.

I ran into a similar limitation with suitcase-jsonl, and the solution was to ensure that the file buffer was flushed to disk upon each new Event or EventPage, like so: https://github.com/bluesky/suitcase-jsonl/pull/11

This makes the _overall_ performance worse (it’s more efficient to flush in larger chunks) but provides the possibility of live “streaming” access, so it should be provided as an option that the user may turn on or off to suit their priorities.
